### ISSUE TITLE
AAI translation into Spanish

### ISSUE THREAD

**Issue by david7670as** [Astorin/AAI-Language-Pack#1]
As a native Spanish speaker, I would love to be able to enjoy your mod in my language. However, I have noticed that currently your mod does not have a version in Spanish.

If you are interested in including a Spanish version of your mod, please let me know and I will gladly send you the Spanish version so that you can incorporate it into your mod. I am sure that many other Spanish-speaking players will appreciate this addition and will value your work even more.

Thank you in advance for your time and consideration. I look forward to hearing from you soon.

**Comment by Astorin** [comment]
Hello.
Of course, the addition of other languages is welcome, the mod was created for this.
Add your language folder in the locale folder (I guess it will be es-ES), translate the source files from the "en (template)" folder, and make a pull request. I will then upload the updated version of the mod to the mod portal.
